[package]
name = "anchoring_sandbox"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
anchoring_service = {version="0.1", path="../", features=["sandbox_tests"]}

bitcoinrpc = {version="0.1", path="../3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "0.8.0"
serde_derive = "0.8.0"
serde_json = "0.8.0"
byteorder = "0.5.0"
log = "0.3.0"
clap = "2.14.0"
rand = "0.3.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"

[dependencies.sandbox]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"

[dependencies.blockchain_explorer]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"