[package]
name = "anchoring_btc_sandbox"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
anchoring_btc_service = {version="0.1", path="../", features=["sandbox_tests"]}

bitcoinrpc = {version="0.1", path="../3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "0.8.0"
serde_derive = "0.8.0"
serde_json = "0.8.0"
byteorder = "1.0.0"
log = "0.3.0"
rand = "0.3.0"
libc = "0.2.21"

[dependencies.exonum]
git = "ssh://git@github.com/alekseysidorov/exonum-core.git"
version = "0.1.0"
rev = "bb1c29a957c5a57a9de2dbccbdbecbb07027d270"

[dependencies.sandbox]
git = "ssh://git@github.com/alekseysidorov/exonum-core.git"
version = "0.1.0"
rev = "bb1c29a957c5a57a9de2dbccbdbecbb07027d270"

[dependencies.blockchain_explorer]
git = "ssh://git@github.com/alekseysidorov/exonum-core.git"
version = "0.1.0"
rev = "bb1c29a957c5a57a9de2dbccbdbecbb07027d270"