[package]
name = "anchoring_btc_sandbox"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
anchoring_btc_service = {version="0.1", path="../", features=["sandbox_tests"]}

bitcoinrpc = {version="0.1", path="../3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
rand = "0.3.0"
libc = "0.2.21"
router = "0.5.1"
iron = "0.5.1"
iron-test = "0.5.0"

[dependencies.exonum]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "ee50943c20f8802af630adb5152d67d763e18fd0"

[dependencies.sandbox]
git = "ssh://git@github.com/exonum/exonum-core.git"
version = "0.1.0"
rev = "ee50943c20f8802af630adb5152d67d763e18fd0"
