language: rust
cache: cargo
sudo: required
dist: trusty
before_install:
- rustup override set nightly-2017-01-08
- rustc --version
- cargo --version
- sudo add-apt-repository -y ppa:chris-lea/libsodium
- sudo apt-add-repository -y ppa:bitcoin/bitcoin
- sudo apt-get -qq update
install:
- sudo apt-get -qq --yes install gcc g++ make libsodium-dev libleveldb-dev libssl-dev
- sudo apt-get -qq --yes install bitcoind
script:
- cargo check --features clippy --verbose
- cargo test --release --verbose
- cargo test --manifest-path sandbox_tests/Cargo.toml --verbose