language: rust
addons:
  apt:
    packages:
    - gcc
    - g++
    - libleveldb-dev
    - libssl-dev
rust:
- stable
cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.local"
  - "$TRAVIS_BUILD_DIR/target"
  - "$TRAVIS_BUILD_DIR/sandbox_tests/target"
sudo: false
env:
  global:
  - RUST_LOG=off
  - CLIPPY_VERS=0.0.154
  - RUSTFMT_VERS=0.9.0
  - LIBSODIUM_VERS=1.0.13
install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VERS/libsodium-$LIBSODIUM_VERS.tar.gz
    tar xvf libsodium-$LIBSODIUM_VERS.tar.gz
    cd libsodium-$LIBSODIUM_VERS
    ./configure --prefix=$HOME/.local
    make -j $(nproc)
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
- |
  if [[ "$FEATURE" == "clippy" ]]; then
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  fi
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    cargo update
  fi
- cargo install --list
script: skip
jobs:
  include:
  - stage: test
    env:
    - FEATURE=fmt
    script:
    - cargo audit
    - cargo fmt -- --write-mode=diff
    - cd sandbox_tests && cargo fmt -- --write-mode=diff
  - stage: test
    rust: nightly-2017-08-27
    env:
    - FEATURE=clippy
    script:
    - cargo clippy -- -D warnings
  - stage: test
    rust: nightly-2017-08-27
    env:
    - FEATURE=clippy
    - SANDBOX=true
    script:
    - cd sandbox_tests && cargo clippy -- -D warnings
  - stage: test
    env:
    - SANDBOX=true
    script:
    - cd sandbox_tests
    - cargo test
  - stage: test
    script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then cargo test; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cargo test --features rpc_tests; fi
notifications:
  slack:
    secure: YHS1dJE+g28M3iW9MG2ShgVd20nHbFLd5i7TbID59RnYl/SAKlGUeTtUTjK0VpnzaTX1ETLSXGcjj7Xx1sI7I/4f1obyMWMEUg7k+JfnkYOcYCiHCymt3L/QK1n8HNbprkrEx8VDO79BzTtB9az0DhQDpf18hJ8VYr3PNxkGgENJNIMf8y1r5/qrp6Tww+/Nw60I1dhdSQCvvZStbQCW47f2pHHcASnUvEpy9CSYjnfgUappMZkZVuYlY8vaV0yB8OrKZSV2nrJwGaoNXkbkYJtCcd4/ZSSGM+hz2dGjmvinjAOpyrUO+TzOHoKBad1/3VRj9ZX5L5CTBfkaeoLEJibdmRu/+0KvtFQFrqskap4CpnKjEh8aeAuYZEWhPy52IQehRF0kyo5ZPwe0pvFZM3KdaMEOT03Pnkqb/UxmsWa/91hC/EIRhWXKk4Y0UWtwhrdnbyKPquasBgZR+0Prh41s966S3MxohsVYPC23jk3vHOZFmNpmoEQsMh5FZgoQUNesVarv8tmQBS5t3kYXRDmrH9J8aLts0ovDT+i1ovmjnog9VOfsEmk8FBlTdkTxtt/x5n0Zf8oEhrgvMp5rB2JvhvxG1iT+GBcJia57yuuOaC0ermGtQqEvSpkQon2IPUtbusaUlt1jEXe3fR91Y11S3PZdX3nuAFnGHyE1pyc=
    rooms:
      secure: RTNYqkHt9BL9IY41uXZzxr472tjxTcv9W1Dy4Un38lwXjzd/+I1E02+RmIR8yogNxwB8IFqVNU1Sc9AQhhpR5iIC35CfQa2PHg/FdT9mVWv3mkxTPjch4i+kvvPwM0E0xE44ZG5tctsEIZrLYXxeeK6kkNB7oIquFHUoOjBW5yFV1yxukNEKvBOMzza1ZRO7ADnN1eHyj4NeWo3SbnNbUR2DeP7v5SA9wk06o9ehsDEDNn+Dvd1eCUx8DLKKo54tGHJC0AMDSDTkcyYWYCmp1XbrwzhuLjaTo07Czuik0FGWe0QiX8HV3v/J140ung7Q/IQLEn/c2kB/BKU26avO8ZodM2wM0hbLiHsI5H0cM6oGzPCMaVBJ7F33EMiWKo2/3/kjg54SvZSjfXROuiBJiKh1CIKaYo2CzIMTpVCmE/PFGCRTleQ2U3ZnxKSHi9qNgIcbTy0XO4oIRRKMgpJXsxjbpxK+pcLN4sP3JEhJbKSvPfye+UOXpGAeGGBKyHDD606WupXXo4GNCxeDxKE4Bfw8zD8r3a81cR1fRZ1jhaHwbn464pIybPcyJfYEhLJCoDYfbUb5+5uFrT54DjWLFtVZK7Tjd5+w59qAWaDvzR5IDB6QK7NLuN+Ngtmn2daEneas4xbYB0JE+ES6t/4beY+3Ftk+k5531KuUVEyvJRg=
