[package]
name = "anchoring_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
exonum = {version="0.1", path="../../exonum"}
blockchain_explorer = {version="0.1", path="../../blockchain_explorer"}
configuration_service = {version="0.1", path="../configuration"}

bitcoinrpc = {version="0.1", path="../../3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "0.8.0"
serde_derive = "0.8.0"
serde_json = "0.8.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.20.5"
iron = "0.5.1"
router = "0.5.1"

[dev-dependencies]
rand = "0.3.0"
env_logger = "0.3.0"
tempdir = "0.3.0"

[features]
default = []
sandbox_tests = []