[package]
name = "anchoring_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@bitfury.com",
           "Aleksey Sidorov <aleksei.sidorov@bitfury.com>"]
readme	= "README.md"           

[dependencies]
bitcoinrpc = {version="0.1", path="3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "0.8.0"
serde_derive = "0.8.0"
serde_json = "0.8.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.20.5"
iron = "0.5.1"
router = "0.5.1"
tempdir = "0.3.0"
rand = "0.3.0"
derive-error = "0.0.3"
clippy = {version = "0.0.107", optional = true}

[dependencies.exonum]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "803f985a556ceeca8ed18256b83f90cfa0b2e370"
version = "0.1.0"

[dependencies.blockchain_explorer]
git = "ssh://git@gitlab.xdev.re/digital-assets/digital-assets.git"
rev = "803f985a556ceeca8ed18256b83f90cfa0b2e370"
version = "0.1.0"

[dependencies.configuration_service]
git = "ssh://git@gitlab.xdev.re/digital-assets/exonum-configuration.git"
rev = "b217524de068eae72de3debf702196e209e0b2b7"
version = "0.1.0"

[dev-dependencies]
env_logger = "0.3.0"

[features]
default = []
sandbox_tests = []
