[package]
name = "anchoring_btc_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]
readme	= "README.md"

[workspace]
members = ["sandbox_tests"]

[dependencies]
bitcoinrpc = {version="0.1", path="3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
tempdir = "0.3.0"
rand = "0.3.0"
derive-error = "0.0.3"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"

[dependencies.exonum]
git = "ssh://git@github.com/darkeld3r/exonum-core.git"
version = "0.1.0"
rev = "aeec8e7b864979d06ac2de5620f8f07f86765e34"

[dependencies.configuration_service]
git = "ssh://git@github.com/darkeld3r/exonum-configuration.git"
version = "0.1.0"
rev = "bf6de201337fc14e7e2e0861087e8d9835e7356c"

[features]
default = []
sandbox_tests = []
