[package]
name = "anchoring_btc_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]
readme	= "README.md"

[workspace]
members = ["sandbox_tests"]

[dependencies]
bitcoinrpc = {version="0.1", path="3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
tempdir = "0.3.0"
rand = "0.3.0"
derive-error = "0.0.3"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"

[dependencies.exonum]
<<<<<<< HEAD
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-core.git"
rev = "7c3d449015a11703330aeb54bf7c50204b273710"

[dependencies.configuration_service]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-configuration.git"
rev = "e1351db2fbf058065c5e216689a7e166088fe5a0"
=======
git = "ssh://git@github.com/vldm/exonum-core.git"
version = "0.1.0"
rev = "985bdae8d4d7622aedc009f96a906f8036bfba4e"

[dependencies.configuration_service]
git = "ssh://git@github.com/gisochre/exonum-configuration.git"
version = "0.1.0"
rev = "d37a1b70d1e88ce39fb78f08492acb78d3fedb70"
>>>>>>> Use refactored messages

[features]
default = []
sandbox_tests = []
