[package]
name = "anchoring_btc_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]
readme	= "README.md"

[workspace]
members = ["sandbox_tests"]

[dependencies]
bitcoinrpc = {version="0.1", path="3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
tempdir = "0.3.0"
rand = "0.3.0"
derive-error = "0.0.3"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"

[dependencies.exonum]
git = "ssh://git@github.com/vldm/exonum-core.git"
version = "0.1.0"
rev = "6eb0ee84af14af7d85c2ad70d426b721bfb6ed3f"

[dependencies.configuration_service]
git = "ssh://git@github.com/gisochre/exonum-configuration.git"
version = "0.1.0"
rev = "47dfb00bdf91b267dfe283c3dbf5fc0b07d4aa78"

[features]
default = []
sandbox_tests = []
