[package]
name = "exonum-btc-anchoring"
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
exonum = "0.1.0"
exonum_bitcoinrpc = "0.1.0"

bitcoin="0.10.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
rand = "0.3.0"
derive-error = "0.0.3"
router = "0.5.1"
iron = "0.5.1"
mount = "0.3.0"
toml = "0.4.0"
tempdir = "0.3.5"

[features]
default = []
sandbox_tests = []
rpc_tests = []

[replace]
# Fix vulnerability
"exonum_bitcoinrpc:0.1.0" = { git = "https://github.com/exonum/bitcoinrpc.git", rev = "0b0d79bde9959539af24b405b6fb81513f67879a" }
"exonum:0.1.0" = { git = "https://github.com/exonum/exonum.git", rev = "64518cec0b091d2eeca6c62356b78dc37d5942ee" }
"exonum-configuration:0.1.0" = { git = "https://github.com/alekseysidorov/exonum-configuration.git", rev = "7a98569f3b84573c25da3477bff88a80bb399668" }

[[example]]
name = "anchoring"

[dev-dependencies]
exonum-configuration = "0.1.0"