[package]
name = "jsonrpc-v1"
version	= "0.2.0"
authors	= ["Andrew Poelstra <apoelstra@wpsoftware.net>", "Jean Pierre De Jesus Dudey Diaz <jeandudey@hotmail.com>"]
license	= "CC0-1.0"
homepage = "https://github.com/jeandudey/jsonrpc-v1/"
repository = "https://github.com/jeandudey/jsonrpc-v1/"
documentation = "http://jeandudey.github.io/jsonrpc-v1/"
description	= "Rust support for the JSON-RPC 1.0 protocol"
keywords = [ "protocol", "json", "http", "jsonrpc" ]
readme	= "README.md"

[lib]
name = "jsonrpc_v1"
path = "src/lib.rs"

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"

[dependencies.hyper]
version = "0.9"
default-features = false

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
